#!/usr/bin/env bash
set -euo pipefail

ROOT=/mnt/weka/home/yongxin.wang/workspace/Auto-claude-code-research-in-sleep/implementation/pcd
TS=${TS:-$(date -u +%Y%m%d_%H%M%S)}
MANIFEST=${MANIFEST:-$ROOT/data/open_data_arena_recovered_scale48k_bal1to1_symthink_20260415_154946/open_data_arena_train_pcd_manifest.jsonl}
EMBEDDING_DIR=${EMBEDDING_DIR:-$ROOT/data/pvrd_sg_text_embeddings_scale30k_20260414_170158/embeddings}
DATASET_DIR=${DATASET_DIR:-/mnt/weka/home/yongxin.wang/workspace/LlamaFactory/data}
DATASET_NAME=${DATASET_NAME:-pvrd_sg_math_thinking_sft_prmlp_scale48k_bal1to1_symthink_${TS}}
MAX_PROMPT_IN_IMAGE=${MAX_PROMPT_IN_IMAGE:-24000}
MAX_ORIGINAL=${MAX_ORIGINAL:-24000}
MAX_GOLD_CHARS=${MAX_GOLD_CHARS:-256}
MAX_THINK_CHARS=${MAX_THINK_CHARS:-1536}
SHORT_THINK_CHARS=${SHORT_THINK_CHARS:-192}
PROMPT_TARGET_MODE=${PROMPT_TARGET_MODE:-think_answer}
ORIGINAL_TARGET_MODE=${ORIGINAL_TARGET_MODE:-think_answer}
ALLOW_SOURCES=${ALLOW_SOURCES:-MMR1,BMMR,Euclid30K,MMK12,FineVision-geo170k(qa),FineVision-geometry3k(mathv360k),WeMath2-Pro,WeMath2-Standard,WeMath2-SFT,mmopenr1-8k}
SEED=${SEED:-42}
CONFIG=${CONFIG:-$ROOT/configs/qwen3vl_pvrd_sg_prmlp_llamafactory_nodz_instruct_scale48k.yaml}
TRAIN_DIR=${TRAIN_DIR:-$ROOT/runs/pvrd_sg_prmlp_nodz_instruct_scale48k_${TS}}
EVAL_DIR=${EVAL_DIR:-$ROOT/lmms_eval_results/pvrd_sg_prmlp_nodz_instruct_scale48k_${TS}_8gpu}
TASKS=${TASKS:-mathvista_testmini_cot,mathvista_testmini_prompt_in_image,mathvision_testmini,mathvision_testmini_prompt_in_image}
NUM_PROCESSES=${NUM_PROCESSES:-8}
DEPENDENCY=${DEPENDENCY:-}
TORCHRUN_LOG_DIR=${TORCHRUN_LOG_DIR:-$ROOT/logs/torchrun_prmlp_scale48k_${TS}}
TORCHRUN_REDIRECTS=${TORCHRUN_REDIRECTS:-3}
TORCHRUN_TEE=${TORCHRUN_TEE:-3}

PRMLP_ENABLED=${PRMLP_ENABLED:-1}
PRMLP_LAMBDA=${PRMLP_LAMBDA:-0.05}
PRMLP_MASK_RATIO=${PRMLP_MASK_RATIO:-0.35}
PRMLP_BLOCK_SIZE=${PRMLP_BLOCK_SIZE:-32}
PRMLP_CUTOFF_LEN=${PRMLP_CUTOFF_LEN:-8192}
PRMLP_PROMPT_TEXT=${PRMLP_PROMPT_TEXT:-Help me solve the problem}
PRMLP_DUMMY_ANSWER=${PRMLP_DUMMY_ANSWER:-0}
PRMLP_IMAGE_MAX_PIXELS=${PRMLP_IMAGE_MAX_PIXELS:-1048576}
PRMLP_IMAGE_MIN_PIXELS=${PRMLP_IMAGE_MIN_PIXELS:-1024}
PRMLP_DEBUG=${PRMLP_DEBUG:-1}
CUDA_LAUNCH_BLOCKING=${CUDA_LAUNCH_BLOCKING:-1}
TORCH_SHOW_CPP_STACKTRACES=${TORCH_SHOW_CPP_STACKTRACES:-1}
PYTHONFAULTHANDLER=${PYTHONFAULTHANDLER:-1}
TORCH_DISTRIBUTED_DEBUG=${TORCH_DISTRIBUTED_DEBUG:-DETAIL}
NCCL_DEBUG=${NCCL_DEBUG:-INFO}

mkdir -p "$ROOT/runs" "$ROOT/lmms_eval_results"

export MANIFEST EMBEDDING_DIR DATASET_DIR DATASET_NAME MAX_PROMPT_IN_IMAGE MAX_ORIGINAL MAX_GOLD_CHARS MAX_THINK_CHARS SHORT_THINK_CHARS PROMPT_TARGET_MODE ORIGINAL_TARGET_MODE ALLOW_SOURCES SEED
SBATCH_ARGS=(--parsable)
if [[ -n "$DEPENDENCY" ]]; then
  SBATCH_ARGS+=(--dependency="$DEPENDENCY")
fi

EXPORT_JOB_ID=$(sbatch "${SBATCH_ARGS[@]}" "$ROOT/scripts/export_llamafactory_pvrd_sg_dataset.slurm.sh")

export CONFIG DATASET_DIR DATASET_NAME OUTPUT_DIR="$TRAIN_DIR"
export PRMLP_ENABLED PRMLP_LAMBDA PRMLP_MASK_RATIO PRMLP_BLOCK_SIZE PRMLP_CUTOFF_LEN PRMLP_PROMPT_TEXT PRMLP_DUMMY_ANSWER PRMLP_IMAGE_MAX_PIXELS PRMLP_IMAGE_MIN_PIXELS
export PRMLP_DEBUG CUDA_LAUNCH_BLOCKING TORCH_SHOW_CPP_STACKTRACES PYTHONFAULTHANDLER TORCH_DISTRIBUTED_DEBUG NCCL_DEBUG
export TORCHRUN_LOG_DIR TORCHRUN_REDIRECTS TORCHRUN_TEE
TRAIN_JOB_ID=$(sbatch --parsable --dependency="afterok:${EXPORT_JOB_ID}" "$ROOT/scripts/llamafactory_qwen3vl_pvrd_sg_sft.slurm.sh")

export MODEL_PATH="$TRAIN_DIR" TASKS OUTPUT_DIR="$EVAL_DIR" NUM_PROCESSES
EVAL_JOB_ID=$(sbatch --parsable --dependency="afterok:${TRAIN_JOB_ID}" "$ROOT/scripts/pvrd_lmms_eval.slurm.sh")

cat <<OUT
MANIFEST=${MANIFEST}
DATASET_NAME=${DATASET_NAME}
TRAIN_DIR=${TRAIN_DIR}
EVAL_DIR=${EVAL_DIR}
EXPORT_JOB_ID=${EXPORT_JOB_ID}
TRAIN_JOB_ID=${TRAIN_JOB_ID}
EVAL_JOB_ID=${EVAL_JOB_ID}
OUT
