#!/usr/bin/env bash
set -euo pipefail

ROOT=/mnt/weka/home/yongxin.wang/workspace/Auto-claude-code-research-in-sleep/implementation/pcd
TS=${TS:-$(date -u +%Y%m%d_%H%M%S)}

DATASET_DIR=${DATASET_DIR:-/mnt/weka/home/yongxin.wang/workspace/LlamaFactory/data}
DATASET_NAME=${DATASET_NAME:-pvrd_sg_math_thinking_sft_prmlp_scale48k_bal1to1_symthink_20260423_052441}
CONFIG=${CONFIG:-$ROOT/configs/qwen3vl_pvrd_sg_prmlp_llamafactory_nodz_instruct_scale48k_stable.yaml}

ABLATION_NAME=${ABLATION_NAME:-vtsw025_pvrdsg}
TRAIN_DIR=${TRAIN_DIR:-$ROOT/runs/pvrd_sg_vtsloss_scale48k_${ABLATION_NAME}_${TS}}
EVAL_BACKEND=${EVAL_BACKEND:-vllm}
EVAL_DIR=${EVAL_DIR:-$ROOT/lmms_eval_results/pvrd_sg_vtsloss_scale48k_${ABLATION_NAME}_${TS}_${EVAL_BACKEND}_parsefix}
TASKS=${TASKS:-mathvista_testmini_cot,mathvista_testmini_prompt_in_image,mathvision_testmini,mathvision_testmini_prompt_in_image}

NPROC_PER_NODE=${NPROC_PER_NODE:-8}
TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE:-8}
DATA_PARALLEL_SIZE=${DATA_PARALLEL_SIZE:-1}
BATCH_SIZE=${BATCH_SIZE:-8}
MAX_MODEL_LEN=${MAX_MODEL_LEN:-32768}
GEN_MAX_NEW_TOKENS=${GEN_MAX_NEW_TOKENS:-1024}
LOG_SAMPLES=${LOG_SAMPLES:-0}
PARSE_REASONING_ANSWER=${PARSE_REASONING_ANSWER:-1}

SBATCH_ACCOUNT=${SBATCH_ACCOUNT:-iq}
SBATCH_TRAIN_TIME=${SBATCH_TRAIN_TIME:-720:00:00}
SBATCH_EVAL_TIME=${SBATCH_EVAL_TIME:-720:00:00}

PVRD_SG_ENABLED=${PVRD_SG_ENABLED:-1}
PVRD_SG_LAMBDA=${PVRD_SG_LAMBDA:-0.15}
PVRD_VTS_SFT_WEIGHT=${PVRD_VTS_SFT_WEIGHT:-0.25}
PVRD_DISTILL_ENABLED=${PVRD_DISTILL_ENABLED:-0}

PRMLP_ENABLED=${PRMLP_ENABLED:-0}
PRMLP_ONLINE_VIEW=${PRMLP_ONLINE_VIEW:-main}
PRMLP_LAMBDA=${PRMLP_LAMBDA:-0.003}
PRMLP_MASK_RATIO=${PRMLP_MASK_RATIO:-0.35}
PRMLP_BLOCK_SIZE=${PRMLP_BLOCK_SIZE:-32}
PRMLP_CUTOFF_LEN=${PRMLP_CUTOFF_LEN:-4096}
PRMLP_EVERY_N_STEPS=${PRMLP_EVERY_N_STEPS:-2}
PRMLP_MAX_MAIN_TOKENS=${PRMLP_MAX_MAIN_TOKENS:-4096}
PRMLP_MAX_EXTRA_TOKENS=${PRMLP_MAX_EXTRA_TOKENS:-2048}
PRMLP_LOG_EVERY_N_STEPS=${PRMLP_LOG_EVERY_N_STEPS:-50}
PRMLP_PROMPT_TEXT=${PRMLP_PROMPT_TEXT:-Help me solve the problem}
PRMLP_DUMMY_ANSWER=${PRMLP_DUMMY_ANSWER:-0}
PRMLP_IMAGE_MAX_PIXELS=${PRMLP_IMAGE_MAX_PIXELS:-262144}
PRMLP_IMAGE_MIN_PIXELS=${PRMLP_IMAGE_MIN_PIXELS:-1024}
PRMLP_DEBUG=${PRMLP_DEBUG:-0}

NCCL_P2P_DISABLE=${NCCL_P2P_DISABLE:-1}
NCCL_ASYNC_ERROR_HANDLING=${NCCL_ASYNC_ERROR_HANDLING:-1}
TORCH_NCCL_ASYNC_ERROR_HANDLING=${TORCH_NCCL_ASYNC_ERROR_HANDLING:-1}
TORCH_DISABLE_ADDR2LINE=${TORCH_DISABLE_ADDR2LINE:-1}

# Full 48K 1:1 run: 48K rows / 8 GPUs = 6000 optimizer steps.
EXTRA_ARGS=${EXTRA_ARGS:-"num_train_epochs=1.0 save_steps=1000 save_total_limit=1 report_to=none"}
MODEL_PATH=${MODEL_PATH:-$TRAIN_DIR/checkpoint-6000}
TORCHRUN_LOG_DIR=${TORCHRUN_LOG_DIR:-$ROOT/logs/torchrun_vtsloss_scale48k_${ABLATION_NAME}_${TS}}
TORCHRUN_REDIRECTS=${TORCHRUN_REDIRECTS:-3}
TORCHRUN_TEE=${TORCHRUN_TEE:-3}
SKIP_ROOT_FINAL_SAVE=${SKIP_ROOT_FINAL_SAVE:-1}

mkdir -p "$ROOT/runs" "$ROOT/lmms_eval_results" "$ROOT/logs" "$ROOT/slurm"

if [[ ! -f "$DATASET_DIR/${DATASET_NAME}.json" ]]; then
  echo "Missing dataset: $DATASET_DIR/${DATASET_NAME}.json" >&2
  exit 2
fi

export CONFIG DATASET_DIR DATASET_NAME OUTPUT_DIR="$TRAIN_DIR"
export NPROC_PER_NODE EXTRA_ARGS
export PVRD_SG_ENABLED PVRD_SG_LAMBDA PVRD_VTS_SFT_WEIGHT PVRD_DISTILL_ENABLED
export PRMLP_ENABLED PRMLP_LAMBDA PRMLP_MASK_RATIO PRMLP_BLOCK_SIZE PRMLP_CUTOFF_LEN
export PRMLP_EVERY_N_STEPS PRMLP_MAX_MAIN_TOKENS PRMLP_MAX_EXTRA_TOKENS PRMLP_LOG_EVERY_N_STEPS
export PRMLP_ONLINE_VIEW PRMLP_PROMPT_TEXT PRMLP_DUMMY_ANSWER PRMLP_IMAGE_MAX_PIXELS PRMLP_IMAGE_MIN_PIXELS PRMLP_DEBUG
export TORCHRUN_LOG_DIR TORCHRUN_REDIRECTS TORCHRUN_TEE SKIP_ROOT_FINAL_SAVE
export NCCL_P2P_DISABLE NCCL_ASYNC_ERROR_HANDLING TORCH_NCCL_ASYNC_ERROR_HANDLING TORCH_DISABLE_ADDR2LINE

TRAIN_JOB_ID=$(
  sbatch --parsable \
    --account="$SBATCH_ACCOUNT" \
    --job-name="vtsloss_${ABLATION_NAME}" \
    --time="$SBATCH_TRAIN_TIME" \
    "$ROOT/scripts/llamafactory_qwen3vl_pvrd_sg_sft.slurm.sh"
)

export MODEL_PATH TASKS OUTPUT_DIR="$EVAL_DIR"
export TENSOR_PARALLEL_SIZE DATA_PARALLEL_SIZE BATCH_SIZE MAX_MODEL_LEN GEN_MAX_NEW_TOKENS LOG_SAMPLES PARSE_REASONING_ANSWER

if [[ "$EVAL_BACKEND" == "vllm" ]]; then
  EVAL_SCRIPT="$ROOT/scripts/pvrd_lmms_eval_vllm.slurm.sh"
elif [[ "$EVAL_BACKEND" == "hf" ]]; then
  EVAL_SCRIPT="$ROOT/scripts/pvrd_lmms_eval.slurm.sh"
else
  echo "Unsupported EVAL_BACKEND=$EVAL_BACKEND; expected vllm or hf" >&2
  exit 2
fi

EVAL_JOB_ID=$(
  sbatch --parsable \
    --account="$SBATCH_ACCOUNT" \
    --job-name="eval_${ABLATION_NAME}" \
    --time="$SBATCH_EVAL_TIME" \
    --dependency="afterok:${TRAIN_JOB_ID}" \
    "$EVAL_SCRIPT"
)

cat <<OUT
ABLATION_NAME=${ABLATION_NAME}
DATASET_NAME=${DATASET_NAME}
CONFIG=${CONFIG}
TRAIN_DIR=${TRAIN_DIR}
MODEL_PATH=${MODEL_PATH}
EVAL_DIR=${EVAL_DIR}
PVRD_SG_LAMBDA=${PVRD_SG_LAMBDA}
PVRD_VTS_SFT_WEIGHT=${PVRD_VTS_SFT_WEIGHT}
PRMLP_ENABLED=${PRMLP_ENABLED}
PRMLP_LAMBDA=${PRMLP_LAMBDA}
PRMLP_ONLINE_VIEW=${PRMLP_ONLINE_VIEW}
PRMLP_EVERY_N_STEPS=${PRMLP_EVERY_N_STEPS}
EXTRA_ARGS=${EXTRA_ARGS}
TRAIN_JOB_ID=${TRAIN_JOB_ID}
EVAL_JOB_ID=${EVAL_JOB_ID}
OUT
