### model
model_name_or_path: Qwen/Qwen3-VL-4B-Instruct
image_max_pixels: 12845056
image_min_pixels: 1024
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: false
freeze_language_model: false

### dataset
dataset: pvrd_sg_math_thinking_sft
dataset_dir: /mnt/weka/home/yongxin.wang/workspace/LlamaFactory/data
template: qwen3_vl
cutoff_len: 8192
preprocessing_num_workers: 8
dataloader_num_workers: 0

### output
output_dir: /mnt/weka/home/yongxin.wang/workspace/Auto-claude-code-research-in-sleep/implementation/pcd/runs/pvrd_sg_prmlp_nodz_instruct_scale48k
logging_steps: 10
save_steps: 200
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 3.0e-6
num_train_epochs: 0.75
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.0
per_device_eval_batch_size: 1
eval_strategy: "no"

### generate
predict_with_generate: false

### extras
logging_first_step: true
disable_gradient_checkpointing: true
ddp_find_unused_parameters: false
